from llama_index.core.tools import FunctionTool
from email.message import EmailMessage
import base64


from service import get_gmail_service


class GoogleTools:
    def __init__(self):
        self.tools = []

        send_mail_tool = FunctionTool.from_defaults(
            fn=self.send_mail,
            description=""" Send an email to a recipient. 
                Inputs required: subject (string), mail_body (string), to (string: recipient email address). 
                IMPORTANT: Refine and finalize the mail_body BEFORE calling this tool, 
                because the tool will not improve or rewrite the text — it will just send it as given. 
                The tool will automatically format the email in HTML and add a disclaimer. 
                Returns a success or failure message.
            """,
        )

        self.tools += [send_mail_tool]

    def send_mail(self, subject: str, mail_body: str, to: str) -> str:
        try:

            gmail = get_gmail_service()
            
            message = EmailMessage()
            html_content = f"""
                    <html>
                    <body>
                        <p>{mail_body}</p>
                        <br><br>
                        <p style="font-size: small; color: gray;">
                        Disclaimer: This mail is generated by my Personal AI agent.
                        </p>
                    </body>
                    </html>
                """
            message.set_content(mail_body)
            message.add_alternative(html_content, subtype="html")

            message["To"] = to
            message["From"] = "rohith171801@gmail.com"
            message["Subject"] = subject

            encoded_msg = base64.urlsafe_b64encode(message.as_bytes()).decode()
            create_msg = {"raw": encoded_msg}

            send_message = (
                gmail.users().messages().send(userId="me", body=create_msg).execute()
            )
            print(f'Message Id: {send_message["id"]}')

            return f"Successfully sent a mail: {to}."
        except Exception as e:
            return f"Failed to send a mail. Error: {str(e)}"
